import type { WizardConfig } from "../types";
import type { GeneratedFile } from "./index";

export function generateNode(c: WizardConfig): {
  files: GeneratedFile[];
  primary: string;
} {
  const ts = c.language === "typescript";
  const ext = ts ? "ts" : "js";
  const files: GeneratedFile[] = [];

  files.push({
    path: `cato-guard.${ext}`,
    language: ts ? "typescript" : "javascript",
    description:
      "Reusable Cato API Guard client. Drop this file into your project and import the CatoGuard class.",
    content: nodeClient(c, ts),
  });

  files.push({
    path: ".env.example",
    language: "ini",
    description:
      "Example env file. Set the guard key here and load via dotenv or your secrets manager.",
    content: `# Cato API Guard\n${c.guardKeyEnvVar}=replace-with-your-guard-key\nCATO_API_URL=${c.apiBaseUrl}\nCATO_TEST_INPUT=\n`,
  });

  files.push({
    path: `test-guard.${ext}`,
    language: ts ? "typescript" : "javascript",
    description:
      "Smoke test against the live Cato endpoint. Set CATO_TEST_INPUT to a value your policy detects.",
    content: nodeTest(c, ts),
  });

  if (c.architecture === "langchain") {
    files.push({
      path: `guarded-chat.${ext}`,
      language: ts ? "typescript" : "javascript",
      description:
        "LangChain.js integration: a chat model wrapper that inspects messages before/after each call.",
      content: nodeLangChain(c, ts),
    });
  } else {
    files.push({
      path: `${integrationFilename(c)}.${ext}`,
      language: ts ? "typescript" : "javascript",
      description:
        "Reference integration showing exactly where to wrap your existing LLM call with guard hooks.",
      content: nodeDirect(c, ts),
    });
  }

  files.push({
    path: "package.json",
    language: "json",
    description:
      "Minimal package.json showing the runtime dependencies introduced by the integration.",
    content: nodePackageJson(c),
  });

  return { files, primary: `cato-guard.${ext}` };
}

function integrationFilename(c: WizardConfig) {
  const map: Record<string, string> = {
    openai: "openai-with-guard",
    anthropic: "anthropic-with-guard",
    "azure-openai": "azure-openai-with-guard",
    bedrock: "bedrock-with-guard",
    gemini: "gemini-with-guard",
    mistral: "mistral-with-guard",
    cohere: "cohere-with-guard",
    ollama: "ollama-with-guard",
    other: "generic-with-guard",
  };
  return map[c.provider] ?? "integration";
}

function header(c: WizardConfig) {
  return [
    "/**",
    ` * Cato API Guard integration`,
    c.customerName ? ` * Customer: ${c.customerName}` : null,
    ` * Stack: ${c.language} · ${c.provider} · ${c.architecture}`,
    ` * Inspection: ${c.inspectionPoints.join(", ")}`,
    ` * Action: ${c.actionMode} · Failure mode: ${c.failureMode}`,
    " * Generated by the Cato API Guard Integration Wizard",
    " * Review with a developer before deploying to production.",
    " */",
  ]
    .filter(Boolean)
    .join("\n");
}

function nodeClient(c: WizardConfig, ts: boolean): string {
  const failOpen = c.failureMode === "fail_open";

  const types = ts
    ? `
export type Role = "system" | "user" | "assistant" | "tool";
export interface CatoMessage { role: Role; content?: string | null; [k: string]: unknown }
export interface GuardDecision {
  blocked: boolean;
  redacted: boolean;
  actionType: string;
  policyName?: string;
  detectionMessage?: string;
  messages: CatoMessage[];
  raw?: unknown;
}
export interface CatoGuardOptions {
  guardKey?: string;
  endpoint?: string;
  timeoutMs?: number;
}
`
    : "";

  const optsType = ts ? ": CatoGuardOptions" : "";
  const msgsType = ts ? ": CatoMessage[]" : "";
  const inspectReturnType = ts ? ": Promise<GuardDecision>" : "";
  const decisionReturnType = ts ? ": GuardDecision" : "";

  return `${header(c)}
${types}
const ENDPOINT = process.env.CATO_API_URL || ${JSON.stringify(c.apiBaseUrl)};
const GUARD_KEY_ENV = ${JSON.stringify(c.guardKeyEnvVar)};

export class CatoGuardConfigurationError extends Error {}
export class CatoGuardUnavailableError extends Error {}

export class CatoGuard {
  ${ts ? "guardKey: string;\n  endpoint: string;\n  timeoutMs: number;" : ""}

  constructor(opts${optsType} = {}) {
    this.guardKey = opts.guardKey || process.env[GUARD_KEY_ENV] || "";
    if (!this.guardKey) {
      throw new Error(\`Cato guard key missing. Set \${GUARD_KEY_ENV} in the environment.\`);
    }
    this.endpoint = opts.endpoint || ENDPOINT;
    this.timeoutMs = opts.timeoutMs ?? 5000;
  }

  async inspect(messages${msgsType}, sessionId${ts ? "?: string" : ""})${inspectReturnType} {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this.timeoutMs);
    const headers${ts ? ": Record<string, string>" : ""} = {
      "Content-Type": "application/json",
      "Authorization": \`Bearer \${this.guardKey}\`,
    };
    if (sessionId) headers["x-cato-session-id"] = sessionId;

    const requestBody = JSON.stringify({ messages });
    let data${ts ? ": any" : ""};
    try {
      const res = await fetch(this.endpoint, {
        method: "POST",
        headers,
        body: requestBody,
        signal: controller.signal,
      });
      const text = await res.text();
      if (res.status === 429 || res.status >= 500) {
        throw new CatoGuardUnavailableError(\`Cato guard unavailable (\${res.status}): \${text.slice(0, 300)}\`);
      }
      if (!res.ok) {
        throw new CatoGuardConfigurationError(\`Cato guard rejected the request (\${res.status}): \${text.slice(0, 500)}\`);
      }
      try {
        data = JSON.parse(text);
      } catch {
        throw new CatoGuardConfigurationError("Cato guard returned a non-JSON success response.");
      }
    } catch (err) {
      if (!isUnavailableError(err)) throw err;
      console.warn("Cato guard unavailable:", err);
      ${
        failOpen
          ? `// fail-open: forward original messages
      return { ...passthrough(messages), actionType: "guard_unavailable", detectionMessage: String(err) } ${ts ? "as GuardDecision" : ""};`
          : `// fail-closed: surface as a blocking decision
      return { blocked: true, redacted: false, actionType: "guard_unavailable", detectionMessage: String(err), messages, raw: null } ${ts ? "as GuardDecision" : ""};`
      }
    } finally {
      clearTimeout(timer);
    }

    return interpret(data, messages);
  }
${
  c.inspectionPoints.includes("system_message")
    ? `
  async inspectSystemMessages(history${msgsType}, sessionId${ts ? "?: string" : ""})${inspectReturnType} {
    const systemMessages = history.filter((m) => m.role === "system");
    if (!systemMessages.length) return passthrough(history);
    const decision = await this.inspect(systemMessages, sessionId);
    if (decision.redacted) {
      const redacted = [...decision.messages];
      decision.messages = history.map((m) => (m.role === "system" ? redacted.shift() ?? m : m));
    } else {
      decision.messages = history;
    }
    return decision;
  }
`
    : ""
}${
  c.inspectionPoints.includes("user_input")
    ? `
  inspectUserInput(history${msgsType}, userText${ts ? ": string" : ""}, sessionId${ts ? "?: string" : ""}) {
    return this.inspect([...history, { role: "user", content: userText }], sessionId);
  }
`
    : ""
}${
    c.inspectionPoints.includes("assistant_output")
      ? `
  inspectAssistantOutput(history${msgsType}, assistantText${ts ? ": string" : ""}, sessionId${ts ? "?: string" : ""}) {
    return this.inspect([...history, { role: "assistant", content: assistantText }], sessionId);
  }
`
      : ""
  }${
    c.inspectionPoints.includes("tool_call_args")
      ? `
  inspectToolCall(history${msgsType}, toolName${ts ? ": string" : ""}, toolArgs${ts ? ": unknown" : ""}, sessionId${ts ? "?: string" : ""}, toolCallId${ts ? "?: string" : ""}) {
    const callId = toolCallId || newSessionId({ prefix: "call" });
    const args = typeof toolArgs === "string" ? toolArgs : JSON.stringify(toolArgs);
    return this.inspect([...history, {
      role: "assistant",
      content: null,
      tool_calls: [{
        id: callId,
        type: "function",
        function: { name: toolName, arguments: args },
      }],
    }], sessionId);
  }
`
      : ""
  }${
    c.inspectionPoints.includes("tool_result")
      ? `
  inspectToolResult(history${msgsType}, toolName${ts ? ": string" : ""}, toolOutput${ts ? ": string" : ""}, sessionId${ts ? "?: string" : ""}, toolCallId${ts ? "?: string" : ""}) {
    const callId = toolCallId || newSessionId({ prefix: "call" });
    return this.inspect([...history, {
      role: "tool",
      tool_call_id: callId,
      name: toolName,
      content: String(toolOutput),
    }], sessionId);
  }
`
      : ""
  }
}

function interpret(data${ts ? ": any" : ""}, original${msgsType})${decisionReturnType} {
  const ra = data?.required_action || {};
  const action = ra.action_type || "pass";
  const redacted = data?.redacted_chat?.all_redacted_messages || [];
  const decision${ts ? ": GuardDecision" : ""} = {
    blocked: false,
    redacted: false,
    actionType: action,
    policyName: ra.policy_name,
    detectionMessage: ra.detection_message,
    messages: original,
    raw: data,
  };
  ${
    c.actionMode === "policy_driven"
      ? `if (action === "block_action") decision.blocked = true;
  else if (action === "redact_action" && redacted.length) { decision.redacted = true; decision.messages = redacted; }`
      : c.actionMode === "block"
        ? `if (action && action !== "pass") decision.blocked = true;`
        : c.actionMode === "redact"
          ? `if (redacted.length) { decision.redacted = true; decision.messages = redacted; }`
          : `if (action && action !== "pass") console.info("Cato detection (log_only):", ra.policy_name, ra.detection_message);`
  }
  return decision;
}

function passthrough(messages${msgsType})${decisionReturnType} {
  return { blocked: false, redacted: false, actionType: "pass", messages, raw: null };
}

function isUnavailableError(err${ts ? ": unknown" : ""}) {
  return err instanceof CatoGuardUnavailableError ||
    (err instanceof Error && err.name === "AbortError") ||
    err instanceof TypeError;
}

export function newSessionId(opts${ts ? ": { userId?: string; conversationId?: string; prefix?: string }" : ""} = {}) {
  const random = globalThis.crypto?.randomUUID?.() ?? \`\${Date.now()}_\${Math.random().toString(36).slice(2)}\`;
  const prefix = opts.prefix || "session";
  ${
    c.sessionIdStrategy === "per_user"
      ? `if (opts.userId) return \`user:\${opts.userId}\`;
  return \`\${prefix}:\${random}\`;`
      : c.sessionIdStrategy === "per_conversation"
        ? `if (opts.conversationId) return \`conversation:\${opts.conversationId}\`;
  return \`\${prefix}:\${random}\`;`
        : `return \`\${prefix}:\${random}\`;`
  }
}
`;
}

function nodeTest(c: WizardConfig, ts: boolean): string {
  return `${header(c)}
import { CatoGuard, newSessionId } from "./cato-guard${ts ? ".js" : ".js"}";

async function main() {
  const testInput = process.env.CATO_TEST_INPUT;
  if (!testInput) {
    console.error("Set CATO_TEST_INPUT to a value your policy detects, then re-run.");
    process.exit(2);
  }
  const guard = new CatoGuard();
  const decision = await guard.inspect(
    [
      { role: "user", content: "Hi" },
      { role: "assistant", content: "Hi, how can I help you?" },
      { role: "user", content: \`Please look up: \${testInput}\` },
    ],
    newSessionId(),
  );
  console.log("Action:    ", decision.actionType);
  console.log("Policy:    ", decision.policyName);
  console.log("Detection: ", decision.detectionMessage);
  console.log("Blocked:   ", decision.blocked);
  console.log("Redacted:  ", decision.redacted);
  console.log("Raw response:");
  console.log(JSON.stringify(decision.raw, null, 2));
}

main().catch((e) => { console.error(e); process.exit(1); });
`;
}

function nodeDirect(c: WizardConfig, ts: boolean): string {
  const provider = providerSnippet(c);
  return `${header(c)}
import { CatoGuard, newSessionId } from "./cato-guard.js";
${provider.imports}

const guard = new CatoGuard();

export async function chat(history${ts ? ": any[]" : ""}, userText${ts ? ": string" : ""}, sessionId${ts ? ": string | undefined" : ""} = undefined, sessionContext${ts ? ": { userId?: string; conversationId?: string }" : ""} = {}) {
  const sid = sessionId || newSessionId(sessionContext);
  let history2 = [...history];

${
  c.inspectionPoints.includes("system_message")
    ? `  // ─── 0. Conversation setup: inspect system messages ─────────
  const systemCheck = await guard.inspectSystemMessages(history2, sid);
  if (systemCheck.blocked) return refusal(systemCheck);
  if (systemCheck.redacted) history2 = systemCheck.messages;

`
    : ""
}${
  c.inspectionPoints.includes("user_input")
    ? `  // ─── 1. Pre-LLM: inspect user input ─────────────────────────
  const pre = await guard.inspectUserInput(history2, userText, sid);
  if (pre.blocked) return refusal(pre);
  history2 = pre.redacted ? pre.messages : [...history2, { role: "user", content: userText }];
`
    : `  history2 = [...history2, { role: "user", content: userText }];
`
}
  // ─── 2. Call the model ───────────────────────────────────────
${provider.call}

${
  c.inspectionPoints.includes("assistant_output")
    ? `  // ─── 3. Post-LLM: inspect assistant output ──────────────────
  const post = await guard.inspectAssistantOutput(history2, assistantText, sid);
  if (post.blocked) return refusal(post);
  if (post.redacted) assistantText = post.messages.at(-1)?.content ?? assistantText;
`
    : ""
}
  return assistantText;
}

function refusal(decision${ts ? ": any" : ""}) {
  return \`I can't help with that - the request was blocked by the safety guard (\${decision.policyName ?? "policy"}: \${decision.detectionMessage ?? "no details"}).\`;
}
`;
}

function providerSnippet(
  c: WizardConfig,
): { imports: string; call: string } {
  switch (c.provider) {
    case "openai":
      return {
        imports: `import OpenAI from "openai";\n\nconst client = new OpenAI();`,
        call: `  const completion = await client.chat.completions.create({
    model: process.env.OPENAI_MODEL || "gpt-4o-mini",
    messages: history2,
  });
  let assistantText = completion.choices[0]?.message?.content ?? "";`,
      };
    case "anthropic":
      return {
        imports: `import Anthropic from "@anthropic-ai/sdk";\n\nconst client = new Anthropic();`,
        call: `  const system = history2.find((m) => m.role === "system")?.content;
  const userMessages = history2.filter((m) => m.role !== "system");
  const completion = await client.messages.create({
    model: process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6",
    system,
    max_tokens: 1024,
    messages: userMessages,
  });
  let assistantText = completion.content
    .filter((b) => b.type === "text")
    .map((b) => b.text)
    .join("");`,
      };
    case "azure-openai":
      return {
        imports: `import { AzureOpenAI } from "openai";\n\nconst client = new AzureOpenAI({\n  apiVersion: process.env.AZURE_OPENAI_API_VERSION || "2024-08-01-preview",\n  endpoint: process.env.AZURE_OPENAI_ENDPOINT,\n});`,
        call: `  const completion = await client.chat.completions.create({
    model: process.env.AZURE_OPENAI_DEPLOYMENT,
    messages: history2,
  });
  let assistantText = completion.choices[0]?.message?.content ?? "";`,
      };
    case "bedrock":
      return {
        imports: `import { BedrockRuntimeClient, InvokeModelCommand } from "@aws-sdk/client-bedrock-runtime";\n\nconst bedrock = new BedrockRuntimeClient({});`,
        call: `  const body = {
    anthropic_version: "bedrock-2023-05-31",
    max_tokens: 1024,
    messages: history2.filter((m) => m.role !== "system"),
  };
  const resp = await bedrock.send(new InvokeModelCommand({
    modelId: process.env.BEDROCK_MODEL_ID || "anthropic.claude-3-5-sonnet-20241022-v2:0",
    body: JSON.stringify(body),
    contentType: "application/json",
  }));
  const payload = JSON.parse(new TextDecoder().decode(resp.body));
  let assistantText = (payload.content || []).map((b) => b.text || "").join("");`,
      };
    case "gemini":
      return {
        imports: `import { GoogleGenerativeAI } from "@google/generative-ai";\n\nconst genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);\nconst model = genAI.getGenerativeModel({ model: process.env.GEMINI_MODEL || "gemini-1.5-pro" });`,
        call: `  const geminiHistory = history2
    .filter((m) => m.role !== "system")
    .map((m) => ({ role: m.role === "user" ? "user" : "model", parts: [{ text: m.content }] }));
  const completion = await model.generateContent({ contents: geminiHistory });
  let assistantText = completion.response.text();`,
      };
    case "mistral":
      return {
        imports: `import { Mistral } from "@mistralai/mistralai";\n\nconst client = new Mistral({ apiKey: process.env.MISTRAL_API_KEY });`,
        call: `  const completion = await client.chat.complete({
    model: process.env.MISTRAL_MODEL || "mistral-large-latest",
    messages: history2,
  });
  let assistantText = completion.choices?.[0]?.message?.content ?? "";`,
      };
    case "cohere":
      return {
        imports: `import { CohereClientV2 } from "cohere-ai";\n\nconst client = new CohereClientV2({ token: process.env.COHERE_API_KEY });`,
        call: `  const completion = await client.chat({
    model: process.env.COHERE_MODEL || "command-r-plus",
    messages: history2,
  });
  let assistantText = completion.message?.content?.map((b) => b.text ?? "").join("") ?? "";`,
      };
    case "ollama":
      return {
        imports: `import OpenAI from "openai";\n\nconst client = new OpenAI({\n  baseURL: process.env.OLLAMA_BASE_URL || "http://localhost:11434/v1",\n  apiKey: process.env.OLLAMA_API_KEY || "ollama",\n});`,
        call: `  const completion = await client.chat.completions.create({
    model: process.env.OLLAMA_MODEL || "llama3.1",
    messages: history2,
  });
  let assistantText = completion.choices[0]?.message?.content ?? "";`,
      };
    default:
      return {
        imports: `// TODO: import the customer's LLM SDK here.`,
        call: `  // TODO: replace with the customer's actual model call.
  let assistantText = await yourModelCall(history2);`,
      };
  }
}

function nodeLangChain(c: WizardConfig, ts: boolean): string {
  return `${header(c)}
import { Runnable, RunnableLambda } from "@langchain/core/runnables";
import { AIMessage, HumanMessage, SystemMessage, ToolMessage } from "@langchain/core/messages";
import { CatoGuard, newSessionId } from "./cato-guard.js";

function toOpenAI(msgs${ts ? ": any[]" : ""}) {
  return msgs.map((m) => {
    if (m instanceof SystemMessage) return { role: "system", content: m.content };
    if (m instanceof HumanMessage) return { role: "user", content: m.content };
    if (m instanceof AIMessage) return { role: "assistant", content: m.content };
    if (m instanceof ToolMessage) return { role: "tool", content: m.content };
    return { role: "user", content: String(m.content ?? "") };
  });
}

function fromOpenAI(msgs${ts ? ": any[]" : ""}) {
  return msgs.map((m) => {
    const content = String(m.content ?? "");
    if (m.role === "system") return new SystemMessage({ content });
    if (m.role === "assistant") return new AIMessage({ content });
    if (m.role === "tool") {
      return new ToolMessage({
        content,
        tool_call_id: m.tool_call_id ?? "cato-redacted-tool",
      });
    }
    return new HumanMessage({ content });
  });
}

export class GuardedChatModel extends Runnable {
  ${ts ? "llm: any;\n  guard: CatoGuard;" : ""}
  lc_namespace = ["cato", "guard"];

  constructor(llm${ts ? ": any" : ""}, guard${ts ? ": CatoGuard | undefined" : ""}) {
    super();
    this.llm = llm;
    this.guard = guard ?? new CatoGuard();
  }

  async invoke(input${ts ? ": any" : ""}, config${ts ? "?: any" : ""}) {
    let messages = Array.isArray(input) ? input : input.toChatMessages?.() ?? input;
    const sid = config?.metadata?.cato_session_id ?? newSessionId();

${
  c.inspectionPoints.includes("user_input") ||
  c.inspectionPoints.includes("system_message")
    ? `    const pre = await this.guard.inspect(toOpenAI(messages), sid);
    if (pre.blocked) return new AIMessage({ content: refusal(pre) });
    if (pre.redacted) messages = fromOpenAI(pre.messages);
`
    : ""
}    const ai = await this.llm.invoke(messages, config);

${
  c.inspectionPoints.includes("assistant_output")
    ? `    const post = await this.guard.inspect(toOpenAI([...messages, ai]), sid);
    if (post.blocked) return new AIMessage({ content: refusal(post) });
    if (post.redacted && post.messages.length) {
      return new AIMessage({ content: post.messages.at(-1)?.content ?? "" });
    }
`
    : ""
}    return ai;
  }
}

export function guardTool(tool${ts ? ": any" : ""}, guard${ts ? ": CatoGuard | undefined" : ""}) {
  const g = guard ?? new CatoGuard();
  return new RunnableLambda({
    func: async (args${ts ? ": any" : ""}) => {
      const sid = newSessionId();
${
  c.inspectionPoints.includes("tool_call_args")
    ? `      const pre = await g.inspectToolCall([], tool.name, args, sid);
      if (pre.blocked) return \`[blocked by safety guard: \${pre.detectionMessage}]\`;
`
    : ""
}      const result = await tool.invoke(args);
${
  c.inspectionPoints.includes("tool_result")
    ? `      const post = await g.inspectToolResult([], tool.name, String(result), sid);
      if (post.blocked) return \`[blocked by safety guard: \${post.detectionMessage}]\`;
      if (post.redacted && post.messages.length) return post.messages.at(-1)?.content;
`
    : ""
}      return result;
    },
  }).withConfig({ runName: \`guarded_\${tool.name}\` });
}

function refusal(decision${ts ? ": any" : ""}) {
  return \`I can't help with that - the request was blocked by the safety guard (\${decision.policyName ?? "policy"}: \${decision.detectionMessage ?? "no details"}).\`;
}
`;
}

function nodePackageJson(c: WizardConfig): string {
  const deps: Record<string, string> = {};
  if (c.provider === "openai" || c.provider === "azure-openai")
    deps["openai"] = "^4.66.0";
  if (c.provider === "ollama") deps["openai"] = "^4.66.0";
  if (c.provider === "anthropic") deps["@anthropic-ai/sdk"] = "^0.32.0";
  if (c.provider === "bedrock") deps["@aws-sdk/client-bedrock-runtime"] = "^3.658.0";
  if (c.provider === "gemini") deps["@google/generative-ai"] = "^0.21.0";
  if (c.provider === "mistral") deps["@mistralai/mistralai"] = "^1.9.0";
  if (c.provider === "cohere") deps["cohere-ai"] = "^7.17.0";
  if (c.architecture === "langchain") {
    deps["@langchain/core"] = "^0.3.0";
  }
  return JSON.stringify(
    {
      name: c.customerName
        ? `${c.customerName.toLowerCase().replace(/\W+/g, "-")}-cato-guard`
        : "cato-guard-integration",
      version: "0.1.0",
      type: "module",
      dependencies: deps,
    },
    null,
    2,
  );
}
