import type { WizardConfig } from "../types";
import type { GeneratedFile } from "./index";

export function generatePython(c: WizardConfig): {
  files: GeneratedFile[];
  primary: string;
} {
  const files: GeneratedFile[] = [];
  files.push({
    path: "cato_guard.py",
    language: "python",
    description:
      "Reusable Cato API Guard client. Drop this file into your project. All inspection helpers and the failure-mode policy live here.",
    content: pythonClient(c),
  });

  files.push({
    path: ".env.example",
    language: "ini",
    description:
      "Example env file. Set the guard key here, then load via python-dotenv or your secrets manager.",
    content: envFile(c),
  });

  files.push({
    path: "test_guard.py",
    language: "python",
    description:
      "Smoke test against the live Cato endpoint. Set CATO_TEST_INPUT to a value your policy is configured to detect (e.g., a sample PII string, a known-bad pattern).",
    content: pythonTest(c),
  });

  if (c.architecture === "direct-sdk") {
    files.push({
      path: integrationFilename(c),
      language: "python",
      description:
        "Reference integration showing exactly where to wrap your existing LLM call with guard hooks.",
      content: pythonDirectIntegration(c),
    });
  } else if (c.architecture === "langchain") {
    files.push({
      path: "guarded_chat.py",
      language: "python",
      description:
        "LangChain integration: a Runnable wrapper that inspects messages before/after each model call and tool node.",
      content: pythonLangChainIntegration(c),
    });
  } else if (c.architecture === "langgraph") {
    files.push({
      path: "guarded_graph.py",
      language: "python",
      description:
        "LangGraph integration: guard nodes you can splice into your StateGraph between agent and tool nodes.",
      content: pythonLangGraphIntegration(c),
    });
  } else {
    files.push({
      path: integrationFilename(c),
      language: "python",
      description:
        "Generic integration recipe - adapt this skeleton to the customer's specific framework.",
      content: pythonDirectIntegration(c),
    });
  }

  return { files, primary: "cato_guard.py" };
}

function integrationFilename(c: WizardConfig) {
  const map: Record<string, string> = {
    openai: "openai_with_guard.py",
    anthropic: "anthropic_with_guard.py",
    "azure-openai": "azure_openai_with_guard.py",
    bedrock: "bedrock_with_guard.py",
    gemini: "gemini_with_guard.py",
    mistral: "mistral_with_guard.py",
    cohere: "cohere_with_guard.py",
    ollama: "ollama_with_guard.py",
    other: "generic_with_guard.py",
  };
  return map[c.provider] ?? "integration.py";
}

function header(c: WizardConfig) {
  const lines = [
    "# ============================================================",
    `# Cato API Guard integration`,
    c.customerName ? `# Customer: ${c.customerName}` : null,
    `# Stack: Python · ${c.provider} · ${c.architecture}`,
    `# Inspection: ${c.inspectionPoints.join(", ")}`,
    `# Action: ${c.actionMode} · Failure mode: ${c.failureMode}`,
    "# Generated by the Cato API Guard Integration Wizard",
    "# Review with a developer before deploying to production.",
    "# ============================================================",
  ].filter(Boolean);
  return lines.join("\n");
}

function pythonClient(c: WizardConfig): string {
  const failOpen = c.failureMode === "fail_open";
  const respectsPolicy = c.actionMode === "policy_driven";
  return `${header(c)}
"""Cato API Guard Python client.

Public API:
    guard = CatoGuard()                                  # reads ${c.guardKeyEnvVar} from env
    decision = guard.inspect(messages, session_id="...") # call before/after the LLM
    if decision.blocked: ...
    safe_messages = decision.messages                     # redacted if action == redact

Inspection points enabled by your wizard config:
    ${c.inspectionPoints.join(", ")}
"""

from __future__ import annotations

import logging
import json
import os
import uuid
from dataclasses import dataclass, field
from typing import Any, Iterable

import requests

logger = logging.getLogger("cato_guard")

CATO_ENDPOINT = os.environ.get(
    "CATO_API_URL",
    ${JSON.stringify(c.apiBaseUrl)},
)
GUARD_KEY_ENV = ${JSON.stringify(c.guardKeyEnvVar)}
DEFAULT_TIMEOUT_SECONDS = 5.0


class CatoGuardError(Exception):
    """Raised when the guard rejects configuration, auth, or payload shape."""


class CatoGuardUnavailableError(CatoGuardError):
    """Raised for transient network, timeout, rate-limit, or 5xx failures."""


@dataclass
class GuardDecision:
    """Result of a single guard inspection."""

    blocked: bool = False
    redacted: bool = False
    action_type: str = "pass"
    policy_name: str | None = None
    detection_message: str | None = None
    messages: list[dict[str, Any]] = field(default_factory=list)
    raw: dict[str, Any] | None = None

    @property
    def safe_to_forward(self) -> bool:
        return not self.blocked


class CatoGuard:
    """Cato API Guard client.

    Defaults match your wizard configuration:
        action_mode   = ${c.actionMode}
        failure_mode  = ${c.failureMode}
    """

    def __init__(
        self,
        guard_key: str | None = None,
        endpoint: str = CATO_ENDPOINT,
        timeout: float = DEFAULT_TIMEOUT_SECONDS,
        action_mode: str = ${JSON.stringify(c.actionMode)},
        failure_mode: str = ${JSON.stringify(c.failureMode)},
    ) -> None:
        self.guard_key = guard_key or os.environ.get(GUARD_KEY_ENV)
        if not self.guard_key:
            raise RuntimeError(
                f"Cato guard key missing. Set {GUARD_KEY_ENV} in the environment."
            )
        self.endpoint = endpoint
        self.timeout = timeout
        self.action_mode = action_mode
        self.failure_mode = failure_mode

    # ------------------------------------------------------------------
    # Core inspection
    # ------------------------------------------------------------------
    def inspect(
        self,
        messages: Iterable[dict[str, Any]],
        session_id: str | None = None,
    ) -> GuardDecision:
        """Inspect a conversation. Returns a GuardDecision.

        The 'messages' arg must be in OpenAI format: a list of dicts with
        at least 'role' and 'content'. Tool calls / tool results should
        also be passed in this list - Cato understands them natively.
        """
        msgs = list(messages)
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {self.guard_key}",
        }
        if session_id:
            headers["x-cato-session-id"] = session_id

        try:
            response = requests.post(
                self.endpoint,
                json={"messages": msgs},
                headers=headers,
                timeout=self.timeout,
            )
        except requests.RequestException as exc:
            return self._handle_unavailable(exc, msgs)

        if response.status_code == 429 or response.status_code >= 500:
            return self._handle_unavailable(
                CatoGuardUnavailableError(
                    f"Cato guard unavailable ({response.status_code}): {response.text[:300]}"
                ),
                msgs,
            )

        if response.status_code >= 400:
            raise CatoGuardError(
                f"Cato guard rejected the request ({response.status_code}): {response.text[:500]}"
            )

        try:
            data = response.json()
        except ValueError as exc:
            raise CatoGuardError("Cato guard returned a non-JSON success response.") from exc

        return self._interpret(data, msgs)

    def _handle_unavailable(self, exc: Exception, msgs: list[dict[str, Any]]) -> GuardDecision:
        logger.warning("Cato guard unavailable: %s", exc)
            ${
              failOpen
                ? `# fail-open: forward original messages
        return GuardDecision(
            action_type="guard_unavailable",
            detection_message=str(exc),
            messages=msgs,
        )`
                : `# fail-closed: block the request
        return GuardDecision(
            blocked=True,
            action_type="guard_unavailable",
            detection_message=str(exc),
            messages=msgs,
        )`
            }

    # ------------------------------------------------------------------
    # Convenience wrappers for each inspection point
    # ------------------------------------------------------------------
${
  c.inspectionPoints.includes("system_message")
    ? `    def inspect_system_messages(self, history, session_id=None):
        original = list(history)
        system_messages = [m for m in original if m.get("role") == "system"]
        if not system_messages:
            return GuardDecision(messages=original)
        decision = self.inspect(system_messages, session_id=session_id)
        if decision.redacted:
            redacted_system = iter(decision.messages)
            decision.messages = [
                next(redacted_system) if m.get("role") == "system" else m
                for m in original
            ]
        else:
            decision.messages = original
        return decision
`
    : ""
}${
  c.inspectionPoints.includes("user_input")
    ? `    def inspect_user_input(self, history, user_text, session_id=None):
        msgs = list(history) + [{"role": "user", "content": user_text}]
        return self.inspect(msgs, session_id=session_id)
`
    : ""
}${
    c.inspectionPoints.includes("assistant_output")
      ? `
    def inspect_assistant_output(self, history, assistant_text, session_id=None):
        msgs = list(history) + [{"role": "assistant", "content": assistant_text}]
        return self.inspect(msgs, session_id=session_id)
`
      : ""
  }${
    c.inspectionPoints.includes("tool_call_args")
      ? `
    def inspect_tool_call(self, history, tool_name, tool_args, session_id=None, tool_call_id=None):
        call_id = tool_call_id or f"call_{uuid.uuid4().hex}"
        arguments = tool_args if isinstance(tool_args, str) else json.dumps(tool_args, sort_keys=True)
        msgs = list(history) + [{
            "role": "assistant",
            "content": None,
            "tool_calls": [{
                "id": call_id,
                "type": "function",
                "function": {
                    "name": tool_name,
                    "arguments": arguments,
                },
            }],
        }]
        return self.inspect(msgs, session_id=session_id)
`
      : ""
  }${
    c.inspectionPoints.includes("tool_result")
      ? `
    def inspect_tool_result(self, history, tool_name, tool_output, session_id=None, tool_call_id=None):
        call_id = tool_call_id or f"call_{uuid.uuid4().hex}"
        msgs = list(history) + [{
            "role": "tool",
            "tool_call_id": call_id,
            "name": tool_name,
            "content": str(tool_output),
        }]
        return self.inspect(msgs, session_id=session_id)
`
      : ""
  }
    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------
    def _interpret(self, data: dict, original: list[dict]) -> GuardDecision:
        action = (data.get("required_action") or {}).get("action_type", "pass")
        policy = (data.get("required_action") or {}).get("policy_name")
        detection = (data.get("required_action") or {}).get("detection_message")
        redacted = (data.get("redacted_chat") or {}).get("all_redacted_messages") or []

        decision = GuardDecision(
            action_type=action,
            policy_name=policy,
            detection_message=detection,
            messages=original,
            raw=data,
        )

        ${
          respectsPolicy
            ? `# policy_driven: honor the action returned by Cato
        if action == "block_action":
            decision.blocked = True
        elif action == "redact_action" and redacted:
            decision.redacted = True
            decision.messages = redacted`
            : c.actionMode === "block"
              ? `# block: any non-pass action becomes a hard block
        if action and action != "pass":
            decision.blocked = True`
              : c.actionMode === "redact"
                ? `# redact: replace messages with the Cato-redacted versions when present
        if redacted:
            decision.redacted = True
            decision.messages = redacted`
                : `# log_only: never block or modify, but log the detection
        if action and action != "pass":
            logger.info("Cato detection (log_only): %s - %s", policy, detection)`
        }

        return decision


def new_session_id(
    user_id: str | None = None,
    conversation_id: str | None = None,
    prefix: str = "session",
) -> str:
    """Generate a Cato session id. Strategy: ${c.sessionIdStrategy}."""
    random_id = str(uuid.uuid4())
    ${
      c.sessionIdStrategy === "per_user"
        ? `if user_id:
        return f"user:{user_id}"
    return f"{prefix}:{random_id}"`
        : c.sessionIdStrategy === "per_conversation"
          ? `if conversation_id:
        return f"conversation:{conversation_id}"
    return f"{prefix}:{random_id}"`
          : `return f"{prefix}:{random_id}"`
    }
`;
}

function envFile(c: WizardConfig) {
  return `# Cato API Guard
${c.guardKeyEnvVar}=replace-with-your-guard-key
CATO_API_URL=${c.apiBaseUrl}

# Optional: a sample sensitive value to use during smoke testing.
# Set this to anything your policy is configured to detect (PII, secrets, etc.).
CATO_TEST_INPUT=
`;
}

function pythonTest(c: WizardConfig) {
  return `${header(c)}
"""Smoke test for the Cato API Guard integration.

Run:
    pip install requests python-dotenv
    export ${c.guardKeyEnvVar}=...
    export CATO_TEST_INPUT='<a value your policy detects>'
    python test_guard.py

The wizard intentionally does NOT bundle a sample sensitive value. Use
any value your policy is configured to flag (PII, secret, etc.).
"""

import json
import os
import sys
from cato_guard import CatoGuard, new_session_id


def main() -> None:
    test_input = os.environ.get("CATO_TEST_INPUT")
    if not test_input:
        print(
            "Set CATO_TEST_INPUT to a value your policy detects, e.g.:\\n"
            "  export CATO_TEST_INPUT='<your test value>'",
            file=sys.stderr,
        )
        sys.exit(2)

    guard = CatoGuard()
    session_id = new_session_id()
    decision = guard.inspect(
        [
            {"role": "user", "content": "Hi"},
            {"role": "assistant", "content": "Hi, how can I help you?"},
            {"role": "user", "content": f"Please look up: {test_input}"},
        ],
        session_id=session_id,
    )
    print("Action:    ", decision.action_type)
    print("Policy:    ", decision.policy_name)
    print("Detection: ", decision.detection_message)
    print("Blocked:   ", decision.blocked)
    print("Redacted:  ", decision.redacted)
    print("Raw response:")
    print(json.dumps(decision.raw, indent=2))


if __name__ == "__main__":
    main()
`;
}

function pythonDirectIntegration(c: WizardConfig): string {
  const provider = providerSnippet(c);
  return `${header(c)}
"""Reference integration: wrap an LLM call with Cato guard hooks.

This file shows exactly where to call the guard. Copy the pattern into
the customer's existing application.
"""

import os
from cato_guard import CatoGuard, new_session_id

${provider.imports}

guard = CatoGuard()


def chat(history, user_text, *, session_id=None, user_id=None, conversation_id=None):
    """End-to-end guarded chat turn."""
    session_id = session_id or new_session_id(
        user_id=user_id,
        conversation_id=conversation_id,
    )
    history = list(history)

${
  c.inspectionPoints.includes("system_message")
    ? `    # ─── 0. Conversation setup: inspect system messages ──────────────
    system_check = guard.inspect_system_messages(history, session_id=session_id)
    if system_check.blocked:
        return _refusal(system_check)
    if system_check.redacted:
        history = system_check.messages

`
    : ""
}${
  c.inspectionPoints.includes("user_input")
    ? `    # ─── 1. Pre-LLM: inspect user input ──────────────────────────────
    pre = guard.inspect_user_input(history, user_text, session_id=session_id)
    if pre.blocked:
        return _refusal(pre)
    # If the policy redacted the message, use the cleaned messages going forward.
    history = pre.messages if pre.redacted else history + [{"role": "user", "content": user_text}]
`
    : `    history = history + [{"role": "user", "content": user_text}]
`
}
    # ─── 2. Call the model ───────────────────────────────────────────
${provider.call}

${
  c.inspectionPoints.includes("assistant_output")
    ? `    # ─── 3. Post-LLM: inspect assistant output ───────────────────────
    post = guard.inspect_assistant_output(history, assistant_text, session_id=session_id)
    if post.blocked:
        return _refusal(post)
    if post.redacted:
        # the last redacted message replaces the assistant turn
        assistant_text = post.messages[-1]["content"]
`
    : ""
}
    return assistant_text


def _refusal(decision):
    return (
        "I can't help with that - the request was blocked by the safety guard "
        f"({decision.policy_name or 'policy'}: {decision.detection_message or 'no details'})."
    )


if __name__ == "__main__":
    print(chat([], "Hello!"))
`;
}

function providerSnippet(c: WizardConfig): { imports: string; call: string } {
  switch (c.provider) {
    case "openai":
      return {
        imports: `from openai import OpenAI

client = OpenAI()`,
        call: `    completion = client.chat.completions.create(
        model=os.environ.get("OPENAI_MODEL", "gpt-4o-mini"),
        messages=history,
    )
    assistant_text = completion.choices[0].message.content or ""`,
      };
    case "anthropic":
      return {
        imports: `import anthropic

client = anthropic.Anthropic()`,
        call: `    # Anthropic separates system from messages - extract if present.
    system = next((m["content"] for m in history if m["role"] == "system"), None)
    user_messages = [m for m in history if m["role"] != "system"]
    completion = client.messages.create(
        model=os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-6"),
        system=system or anthropic.NOT_GIVEN,
        max_tokens=1024,
        messages=user_messages,
    )
    assistant_text = "".join(b.text for b in completion.content if hasattr(b, "text"))`,
      };
    case "azure-openai":
      return {
        imports: `from openai import AzureOpenAI

client = AzureOpenAI(
    api_version=os.environ.get("AZURE_OPENAI_API_VERSION", "2024-08-01-preview"),
    azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],
)`,
        call: `    completion = client.chat.completions.create(
        model=os.environ["AZURE_OPENAI_DEPLOYMENT"],
        messages=history,
    )
    assistant_text = completion.choices[0].message.content or ""`,
      };
    case "bedrock":
      return {
        imports: `import boto3, json

bedrock = boto3.client("bedrock-runtime")`,
        call: `    body = {
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 1024,
        "messages": [m for m in history if m["role"] != "system"],
    }
    resp = bedrock.invoke_model(
        modelId=os.environ.get("BEDROCK_MODEL_ID", "anthropic.claude-3-5-sonnet-20241022-v2:0"),
        body=json.dumps(body),
    )
    payload = json.loads(resp["body"].read())
    assistant_text = "".join(b.get("text", "") for b in payload.get("content", []))`,
      };
    case "gemini":
      return {
        imports: `import google.generativeai as genai

genai.configure(api_key=os.environ["GEMINI_API_KEY"])
model = genai.GenerativeModel(os.environ.get("GEMINI_MODEL", "gemini-1.5-pro"))`,
        call: `    # Gemini takes a flat list of {role, parts}.
    gemini_history = [
        {"role": "user" if m["role"] == "user" else "model", "parts": [m["content"]]}
        for m in history if m["role"] != "system"
    ]
    completion = model.generate_content(gemini_history)
    assistant_text = completion.text`,
      };
    case "mistral":
      return {
        imports: `from mistralai import Mistral

client = Mistral(api_key=os.environ["MISTRAL_API_KEY"])`,
        call: `    completion = client.chat.complete(
        model=os.environ.get("MISTRAL_MODEL", "mistral-large-latest"),
        messages=history,
    )
    assistant_text = completion.choices[0].message.content or ""`,
      };
    case "cohere":
      return {
        imports: `import cohere

client = cohere.ClientV2(api_key=os.environ["COHERE_API_KEY"])`,
        call: `    completion = client.chat(
        model=os.environ.get("COHERE_MODEL", "command-r-plus"),
        messages=history,
    )
    assistant_text = completion.message.content[0].text`,
      };
    case "ollama":
      return {
        imports: `from openai import OpenAI

client = OpenAI(
    base_url=os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434/v1"),
    api_key=os.environ.get("OLLAMA_API_KEY", "ollama"),
)`,
        call: `    completion = client.chat.completions.create(
        model=os.environ.get("OLLAMA_MODEL", "llama3.1"),
        messages=history,
    )
    assistant_text = completion.choices[0].message.content or ""`,
      };
    default:
      return {
        imports: `# TODO: import your customer's LLM SDK here.`,
        call: `    # TODO: replace with the customer's actual model call.
    assistant_text = your_model_call(history)`,
      };
  }
}

function pythonLangChainIntegration(c: WizardConfig): string {
  return `${header(c)}
"""LangChain integration for Cato API Guard.

This wraps a ChatModel with pre/post inspection. Drop it in wherever
the customer constructs their chain.
"""

from langchain_core.messages import (
    AIMessage,
    BaseMessage,
    HumanMessage,
    SystemMessage,
    ToolMessage,
)
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.runnables import Runnable, RunnableLambda

from cato_guard import CatoGuard, new_session_id


def _to_openai_format(msgs: list[BaseMessage]) -> list[dict]:
    out = []
    for m in msgs:
        if isinstance(m, SystemMessage):
            out.append({"role": "system", "content": m.content})
        elif isinstance(m, HumanMessage):
            out.append({"role": "user", "content": m.content})
        elif isinstance(m, AIMessage):
            out.append({"role": "assistant", "content": m.content})
        elif isinstance(m, ToolMessage):
            out.append({"role": "tool", "content": m.content})
    return out


def _from_openai_format(msgs: list[dict]) -> list[BaseMessage]:
    out = []
    for m in msgs:
        content = m.get("content") or ""
        role = m.get("role")
        if role == "system":
            out.append(SystemMessage(content=content))
        elif role == "assistant":
            out.append(AIMessage(content=content))
        elif role == "tool":
            out.append(ToolMessage(
                content=content,
                tool_call_id=m.get("tool_call_id", "cato-redacted-tool"),
            ))
        else:
            out.append(HumanMessage(content=content))
    return out


class GuardedChatModel(Runnable):
    """LangChain Runnable that wraps a chat model with Cato guard hooks."""

    def __init__(self, llm: BaseChatModel, guard: CatoGuard | None = None):
        self.llm = llm
        self.guard = guard or CatoGuard()

    def invoke(self, input, config=None, **kwargs):  # type: ignore[override]
        messages = list(input) if isinstance(input, list) else input.to_messages()
        session_id = (config or {}).get("metadata", {}).get("cato_session_id") or new_session_id()

${
  c.inspectionPoints.includes("user_input") ||
  c.inspectionPoints.includes("system_message")
    ? `        pre = self.guard.inspect(_to_openai_format(messages), session_id=session_id)
        if pre.blocked:
            return AIMessage(content=_refusal(pre))
        if pre.redacted:
            messages = _from_openai_format(pre.messages)
`
    : ""
}
        ai = self.llm.invoke(messages, config=config, **kwargs)

${
  c.inspectionPoints.includes("assistant_output")
    ? `        post = self.guard.inspect(
            _to_openai_format(messages + [ai]),
            session_id=session_id,
        )
        if post.blocked:
            return AIMessage(content=_refusal(post))
        if post.redacted and post.messages:
            return AIMessage(content=post.messages[-1].get("content") or "")
`
    : ""
}
        return ai


def _refusal(decision):
    return (
        "I can't help with that - the request was blocked by the safety guard "
        f"({decision.policy_name or 'policy'}: {decision.detection_message or 'no details'})."
    )


def guard_tool(tool, guard: CatoGuard | None = None) -> Runnable:
    """Wrap a LangChain tool so its inputs and outputs pass through Cato.

    Use this on tools that touch sensitive data:
        guarded_search = guard_tool(search_tool)
    """
    guard = guard or CatoGuard()

    def _run(args):
        session_id = new_session_id()
${
  c.inspectionPoints.includes("tool_call_args")
    ? `        pre = guard.inspect_tool_call([], tool.name, str(args), session_id=session_id)
        if pre.blocked:
            return f"[blocked by safety guard: {pre.detection_message}]"
`
    : ""
}        result = tool.invoke(args)
${
  c.inspectionPoints.includes("tool_result")
    ? `        post = guard.inspect_tool_result([], tool.name, str(result), session_id=session_id)
        if post.blocked:
            return f"[blocked by safety guard: {post.detection_message}]"
        if post.redacted and post.messages:
            return post.messages[-1]["content"]
`
    : ""
}        return result

    return RunnableLambda(_run).with_config(run_name=f"guarded_{tool.name}")
`;
}

function pythonLangGraphIntegration(c: WizardConfig): string {
  return `${header(c)}
"""LangGraph guard nodes.

Splice these nodes into your StateGraph between the agent and tool nodes
to enforce inspection at every transition.
"""

from typing import Literal
from langgraph.graph import END
from cato_guard import CatoGuard, new_session_id

guard = CatoGuard()


def pre_model_node(state: dict) -> dict:
${
  c.inspectionPoints.includes("user_input")
    ? `    """Inspect the user-side state before calling the model."""
    session_id = state.get("cato_session_id") or new_session_id()
    decision = guard.inspect(state["messages"], session_id=session_id)
    if decision.blocked:
        state["messages"].append({
            "role": "assistant",
            "content": f"[blocked: {decision.detection_message}]",
        })
        state["__halt__"] = True
    elif decision.redacted:
        state["messages"] = decision.messages
    state["cato_session_id"] = session_id
    return state
`
    : `    return state
`
}

def post_model_node(state: dict) -> dict:
${
  c.inspectionPoints.includes("assistant_output")
    ? `    """Inspect the latest assistant message."""
    session_id = state.get("cato_session_id") or new_session_id()
    decision = guard.inspect(state["messages"], session_id=session_id)
    if decision.blocked:
        state["messages"][-1] = {
            "role": "assistant",
            "content": f"[blocked: {decision.detection_message}]",
        }
        state["__halt__"] = True
    elif decision.redacted:
        state["messages"] = decision.messages
    return state
`
    : `    return state
`
}

def pre_tool_node(state: dict) -> dict:
${
  c.inspectionPoints.includes("tool_call_args")
    ? `    """Inspect tool call arguments before the tool executes."""
    last = state["messages"][-1]
    tool_calls = getattr(last, "tool_calls", None) or last.get("tool_calls") or []
    session_id = state.get("cato_session_id") or new_session_id()
    for tc in tool_calls:
        decision = guard.inspect_tool_call(
            state["messages"][:-1],
            tc.get("name", "unknown"),
            tc.get("args", {}),
            session_id=session_id,
            tool_call_id=tc.get("id"),
        )
        if decision.blocked:
            state["__halt__"] = True
            state["messages"].append({
                "role": "tool",
                "content": f"[blocked: {decision.detection_message}]",
            })
            break
    return state
`
    : `    return state
`
}

def post_tool_node(state: dict) -> dict:
${
  c.inspectionPoints.includes("tool_result")
    ? `    """Inspect tool results before they re-enter the model context."""
    session_id = state.get("cato_session_id") or new_session_id()
    last = state["messages"][-1]
    if last.get("role") == "tool":
        decision = guard.inspect_tool_result(
            state["messages"][:-1],
            last.get("name", "unknown"),
            last.get("content", ""),
            session_id=session_id,
            tool_call_id=last.get("tool_call_id"),
        )
        if decision.blocked:
            state["messages"][-1] = {
                "role": "tool",
                "content": f"[blocked: {decision.detection_message}]",
            }
        elif decision.redacted and decision.messages:
            state["messages"][-1] = decision.messages[-1]
    return state
`
    : `    return state
`
}

def halt_router(state: dict) -> Literal["__end__", "continue"]:
    return END if state.get("__halt__") else "continue"


# Example wiring (uncomment and adapt to the customer's graph):
# from langgraph.graph import StateGraph
# graph = StateGraph(MyState)
# graph.add_node("pre_model", pre_model_node)
# graph.add_node("agent", agent_node)
# graph.add_node("post_model", post_model_node)
# graph.add_node("pre_tool", pre_tool_node)
# graph.add_node("tools", tool_node)
# graph.add_node("post_tool", post_tool_node)
# graph.set_entry_point("pre_model")
# graph.add_edge("pre_model", "agent")
# graph.add_edge("agent", "post_model")
# graph.add_conditional_edges("post_model", lambda s: "pre_tool" if needs_tool(s) else END)
# graph.add_edge("pre_tool", "tools")
# graph.add_edge("tools", "post_tool")
# graph.add_edge("post_tool", "pre_model")
`;
}
